### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by alexbprofit** [umbresp/brawlstars#7]
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\brawlstars\client.py", line 66, in get_player
    raise HTTPError(resp.status_code)
  File "C:\Python39\lib\site-packages\brawlstars\errors.py", line 29, in __init__
    self.error = 'An error occurred. Status: ' + code
TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\prog\PycharmProjects\untitled3\brawltracker.py", line 4, in <module>
    player = client.get_player(tag="Q8P2ULP")
  File "C:\Python39\lib\site-packages\brawlstars\client.py", line 72, in get_player
    raise Timeout()
brawlstars.errors.Timeout

Process finished with exit code 1.

code must be str?

**Comment by terexdev** [comment]
bruh
